#' MEGA data read-in
#' 
#' @param analysis_file Filename of MAO file generated by prototyper
#' @param data Data object
#' @param data_ext Datatype of input data, for writing
#' @param out_file Name of temporary output file
#' @param out_parse Datatype of MEGA output
#' 
#' @return Data from MEGA
#' 
#' @author Jared Knoblauch
#' 
#' @export
#' @import ape
#' 
#' 

runMegaOnData <- function(data,data_ext,analysis_file,out_prefix="mega_out_",temp_prefix="mega_temp") {
  temp_fn = paste(temp_prefix,'.',data_ext,sep="")
  print(temp_fn)
  if (data_ext == 'fasta') {
    write.FASTA(data,temp_fn)
  }
  out_objects = runMega(analysis_file,temp_fn)
  return(out_objects)
}
